
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             100
     no. of nonzeroes in lower triangle of a =             288
     no. of nonzeroes in the factor l        =            1236
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =              25
     maximum order of a front matrix         =              22
     maximum size of a front matrix          =             253
     maximum size of a front trapezoid       =             250
     no. of floating point ops for factor    =      6.9500D+03
     no. of floating point ops for solve     =      2.3560D+03
     ratio of flops for factor (min/max)     =          1.0000
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.008000
     time (cpu & wall) for ordering          =        0.015625        0.022000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     no input or output performed

  Total Solver Memory allocated              =        0.082 MB
